### ISSUE TITLE
New Install missing package

### ISSUE THREAD

**Issue by jvherring** [butlerx/wetty#161]
New Install of latest using npm -g
launching: node wetty.js gives:
[root@webserver wetty]# node index.js
module.js:478
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/spool/apps/wetty/index.js:4:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

yargs is located/installed by the npm install into:
/usr/lib/node_modules/wetty.js/node_modules/yargs

What am I missing here?  I did all installation steps as root.
Help would be appreciated.

**Comment by jvherring** [comment]
This was related to a yarn build issue, and has been resolved.

**Comment by sunbart** [comment]
I get the same error after installing with `sudo npm i -g wetty`. 

First the error looked exactly the same as the above (with the line numbers slightly shifted), but after updating node to version 12.13.0, the format changed, but the error persists.
